/**
 * PromptChain Codama Client Generator
 *
 * Generates TypeScript and Rust clients from Anchor IDL files
 * using the Codama rendering framework.
 *
 * Usage: npx tsx generate.ts
 */

import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface CodamaConfig {
  programs: Array<{
    name: string;
    idl: string;
    programId: string;
  }>;
  renderers: {
    typescript?: {
      outDir: string;
      [key: string]: unknown;
    };
    rust?: {
      outDir: string;
      [key: string]: unknown;
    };
  };
}

function loadConfig(): CodamaConfig {
  const configPath = join(__dirname, 'codama.json');
  const raw = readFileSync(configPath, 'utf-8');
  return JSON.parse(raw);
}

function resolvePath(p: string): string {
  return join(__dirname, p);
}

function ensureDir(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function mapAnchorTypeToTs(anchorType: string): string {
  const typeMap: Record<string, string> = {
    publicKey: 'PublicKey',
    string: 'string',
    u8: 'number',
    u16: 'number',
    u32: 'number',
    u64: 'bigint | number',
    i8: 'number',
    i16: 'number',
    i32: 'number',
    i64: 'bigint | number',
    bool: 'boolean',
    bytes: 'Uint8Array',
  };
  return typeMap[anchorType] || 'unknown';
}

function generateTypeScriptTypes(config: CodamaConfig): void {
  if (!config.renderers.typescript) return;

  const outDir = resolvePath(config.renderers.typescript.outDir);
  ensureDir(outDir);

  let output = `// Auto-generated by PromptChain Codama Generator
// Do not edit manually

import { PublicKey } from '@solana/web3.js';

`;

  for (const program of config.programs) {
    const idlPath = resolvePath(program.idl);
    if (!existsSync(idlPath)) {
      console.warn(`  ⚠ IDL not found: ${idlPath}`);
      continue;
    }

    const idl = JSON.parse(readFileSync(idlPath, 'utf-8'));

    output += `// === Program: ${program.name} ===\n`;
    output += `export const ${program.name}_PROGRAM_ID = new PublicKey('${program.programId}');\n\n`;

    // Generate account types
    if (idl.accounts) {
      for (const account of idl.accounts) {
        const name = account.name.charAt(0).toUpperCase() + account.name.slice(1);
        output += `export interface ${name} {\n`;
        if (account.type?.fields) {
          for (const field of account.type.fields) {
            const tsType = mapAnchorTypeToTs(field.type);
            output += `  ${field.name}: ${tsType};\n`;
          }
        }
        output += `}\n\n`;
      }
    }

    // Generate instruction types
    if (idl.instructions) {
      output += `// Instructions\n`;
      for (const ix of idl.instructions) {
        output += `export type ${ix.name}Instruction = {\n`;
        output += `  programId: PublicKey;\n`;
        output += `  accounts: Array<{ pubkey: PublicKey; isSigner: boolean; isWritable: boolean }>;\n`;
        output += `  data: Uint8Array;\n`;
        output += `};\n\n`;
      }
    }
  }

  const tsPath = join(outDir, 'types.ts');
  writeFileSync(tsPath, output);
  console.log(`  ✓ TypeScript types written to ${tsPath}`);
}

function generateRustTypes(config: CodamaConfig): void {
  if (!config.renderers.rust) return;

  const outDir = resolvePath(config.renderers.rust.outDir);
  ensureDir(outDir);

  let output = `// Auto-generated by PromptChain Codama Generator
// Do not edit manually

use solana_sdk::pubkey::Pubkey;
use borsh::{BorshSerialize, BorshDeserialize};

`;

  for (const program of config.programs) {
    const idlPath = resolvePath(program.idl);
    if (!existsSync(idlPath)) {
      console.warn(`  ⚠ IDL not found: ${idlPath}`);
      continue;
    }

    const idl = JSON.parse(readFileSync(idlPath, 'utf-8'));
    const progConst = program.name.toUpperCase();

    output += `pub const ${progConst}_PROGRAM_ID: &str = "${program.programId}";\n\n`;

    // Generate account structs
    if (idl.accounts) {
      for (const account of idl.accounts) {
        const name = account.name.charAt(0).toUpperCase() + account.name.slice(1);
        output += `#[derive(Debug, Clone, BorshSerialize, BorshDeserialize, PartialEq)]\n`;
        output += `pub struct ${name} {\n`;
        if (account.type?.fields) {
          for (const field of account.type.fields) {
            const rustType = mapAnchorTypeToRust(field.type);
            output += `    pub ${field.name}: ${rustType},\n`;
          }
        }
        output += `}\n\n`;
      }
    }
  }

  const rsPath = join(outDir, 'mod.rs');
  writeFileSync(rsPath, output);
  console.log(`  ✓ Rust types written to ${rsPath}`);
}

function mapAnchorTypeToRust(anchorType: string): string {
  const typeMap: Record<string, string> = {
    publicKey: 'Pubkey',
    string: 'String',
    u8: 'u8',
    u16: 'u16',
    u32: 'u32',
    u64: 'u64',
    i8: 'i8',
    i16: 'i16',
    i32: 'i32',
    i64: 'i64',
    bool: 'bool',
    bytes: 'Vec<u8>',
  };
  return typeMap[anchorType] || 'String';
}

function main(): void {
  console.log('🔧 PromptChain Codama Client Generator\n');
  console.log('Loading configuration...');
  const config = loadConfig();
  console.log(`  Found ${config.programs.length} program(s)\n`);

  console.log('Generating TypeScript types...');
  generateTypeScriptTypes(config);

  console.log('\nGenerating Rust types...');
  generateRustTypes(config);

  console.log('\n✅ Client generation complete!');
  console.log('  Next steps:');
  console.log('  1. Verify the generated types match your on-chain programs');
  console.log('  2. Run anchor build to regenerate IDLs before code generation');
  console.log('  3. Commit the generated files alongside your Anchor programs');
}

main();
