[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
promptchain = "D7zeVCj96CQx1xBEm7EEzVLXw4sNukdykxN7ErmxjF3F"
promptchain_curation = "2eWqZR6HriWjKJs5MozSZKERxP98JM7FEwn8FA7Hh1cK"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx ./node_modules/.bin/mocha --timeout 1000000 tests/integration/**/*.test.ts"
